### ISSUE TITLE
Deken-0.9 crashes with Pd-0.51-3

### ISSUE THREAD

**Issue by incalcando** [pure-data/deken#275] opened 2022-05-27 09:32 UTC
installed deken v0.9 for Pd-0.51-3 running on a Mac M1 with Big Sur (v11.4)

Opening deken (Help>Find Externals) crashes Pd

[Deken-CrashLog.txt](https://github.com/pure-data/deken/files/8785567/Deken-CrashLog.txt)

Installing and running Deken in Pd-0.52-2 is working as expected and described.

**Comment by umlaeute** [comment] 2022-05-29 21:55
I can reproduce this with Pd-0.51-3 (on amd64), which ships Tcl/Tk-8.6.10.
It also crashes on Pd-0.52-2-macosx7, which also ships Tcl/Tk-8.6.10 (so I guess the Tcl/Tk version is to blame here).
Funnily enough, everything seems to work as expected on Pd-0.52.2-i386, which ships **Tcl/Tk-8.5.19**.

| Tcl/Tk | works? |
|----------|------------|
| 8.5.9 | :tada: |
| 8.6.10 | :boom: |
| 8.6.12 |:tada: |

so it seems to be some weird regression in Tcl/Tk

**Comment by umlaeute** [comment] 2022-05-30 07:15
so i tried all available Pd versions that would run on my amd64 CPU:

|  Pd               |       Tcl/Tk         |       status  |
|  -------------    |       -------------  |       ------  |
|  0.48-0           |       8.5.19         |       :tada:  |
|  0.48-1           |       8.5.19         |       :tada:  |
|  0.48-2           |       8.5.19         |       :tada:  |
|                   |                      |               |
|  0.49-0           |       8.5.19         |       :tada:  |
|  0.49-1           |       8.5.19         |       :tada:  |
|                   |                      |               |
|  0.50-0           |       8.5.19         |       :tada:  |
|  0.50-1           |       8.5.19         |       :tada:  |
|  0.50-2           |       8.5.19         |       :tada:  |
|                   |                      |               |
|  0.51-0           |       8.5.19         |       :tada:  |
|  0.51-1           |       8.6.10         |       :boom:  |
|  0.51-2           |       8.6.10         |       :boom:  |
|  0.51-3           |       8.6.10         |       :boom:  |
|  0.51-4           |       8.6.10         |       :tada:  |
|                   |                      |               |
|  0.52-1-really    |       8.6.12         |       :tada:  |
|  0.52-1-macosx7|  8.6.10  |              :boom:  |       
|  0.52-2           |       8.6.12         |       :tada:  |
|  0.52-2-macosx7|  8.6.10  |              :boom:  |       


the *really* interesting question is, why Pd-0.51-4 (which comes with Tcl/Tk-8.6.10) does **not** crash...

**Comment by umlaeute** [comment] 2022-05-30 07:25
the riddle might be solved as follows:
- @danomatika added a few patches for Tcl/Tk-8.6.10 to the Pd respository, namely
  - helpmenu.patch ("Fixes help menu items disabling after switching windows")
  - scrollbars.patch ("fixes scrollbars not (re)drawing")
  - zombiewindows.patch ("fix for zombie windows on systems with the Touchbar which could cause Pd to crash when closing the Font dialog due to a nil window pointer")

so i think that one of these patches (most likely "zombiewindows") fixes the crash, but it has not been applied to the binaries built by miller (in the 0.52 series)

**Closed** 2022-05-30 12:23 UTC
Labels: bug, deken-plugin

**Comment by danomatika** [comment] 2022-05-30 12:25
We moved to 8.6.12 and I checked if all of the patches were no longer needed. I believe everything was fixed but perhaps the zombie windows fix is still needed?

**Comment by umlaeute** [comment] 2022-05-30 12:47
the thing is, that for the legacy builds (OSX-10.7, i386), @millerpuckette does not use Tcl/Tk-8.6.12 but apparently some Tcl/Tk-8.6.10 build (and i think he is using some pre-built binary, so the patches are not applied at all).

for the problem at hand, it wouldn't help much if the patches were applied for future releases *unless accompanied with some version bump* so the `deken-plugin.tcl` (externally installed, rather than the one shipped with Pd) must make sure not to crash when running on an old version of Pd (that comes with the unpatched Tcl/Tk-8.6.10)

**Comment by danomatika** [comment] 2022-05-30 13:15
I assume he uses the Wish.app build which is compressed in the `mac/stuff/` tarball. What has probably happened is that build was made before all the patches were added and/or it doesn't incorporate them, so needs to be updated.

**Comment by umlaeute** [comment] 2022-05-31 13:37
@incalcando would it be possible to test the latest and greatest, unreleased deken plugin?

for this, please follow the instructions in the [README](https://github.com/pure-data/deken#downloadinstall) (specifically the part about the *manual installation*). make sure to replace the existing `deken-plugin.tcl` (presumably in `~/Documents/Pd/externals/deken-plugin/`) with the downloaded file...

(To check whether you got the correct version: you should see something like "[deken] installed version [...] < 0.9.1...overwriting" in the Pd-console (if you raise the verbosity to at least "debug" level))

**Comment by incalcando** [comment] 2022-05-31 21:27
yes, this one works for me here now for pd_0.51-3 as well as pd_0.52-2

thanks!

Sebastian

umläute wrote on 31/05/2022 14:37:
