### ISSUE TITLE
missing sources

### ISSUE THREAD

**Issue by avilleret** [pure-data/deken#118] opened 2016-02-15 01:25 UTC
I tried to upload Gem directly from my RPi but I always get the error : 

~~~~
$ deken upload "Gem-v0.93.3-(Linux-armv6-32)-externals.tar.gz"
Deken 0.1
Environment variable DEKEN_USERNAME is not set and the config file /home/pi/.deken/config does not contain a 'username = ...' entry.
To avoid this prompt in future please add a setting to the config or environment.
Please enter username for http://puredata.info/: aviilleret
Please enter password for uploading as 'aviilleret':
Checking puredata.info for Source package for 'Gem/0.93.3'
Missing sources for 'Gem/0.93.3'!
~~~~

I understood that I need to upload the sources with the binary package for licence reason.
So do I but I got the same error :

~~~~
$ deken upload "Gem-v0.93.3git54b4b7c-(Linux-armv6-32)-externals.tar.gz" "Gem-v0.93.3git54b4b7c-(Source)-externals.tar.gz"
Deken 0.1
Environment variable DEKEN_USERNAME is not set and the config file /home/pi/.deken/config does not contain a 'username = ...' entry.
To avoid this prompt in future please add a setting to the config or environment.
Please enter username for http://puredata.info/: avilleret
Please enter password for uploading as 'avilleret':
Checking puredata.info for Source package for 'Gem/0.93.3git54b4b7c'
Missing sources for 'Gem/0.93.3git54b4b7c'!
~~~~

Is this a bug, or did I miss a step ?

**Comment by avilleret** [comment] 2016-02-15 01:33
finally I uploaded it without sources archive manually : http://puredata.info/Members/avilleret/software/Gem/

**Comment by umlaeute** [comment] 2016-02-15 13:22
it's a feature (see #88).

[i don't see](http://deken.puredata.info/search?name=Gem) that you have uploaded any sources for `Gem/0.93.3git54b4b7c`, so `deken` is correct in complaining that the sources are missing.
(deken is dumb; it won't read your version string, see that it contains `git`, google for the upstream repository and check whether the commit-id has been pushed; it also won't read your notes, mind or file-descriptions and parse it for terms like *here are the source:*)

In any case, you can override the complaint with the `--no-source-warning` flag.

I'm reluctant to add this info to the error message itself, as i really want people to upload the sources.
(not only for license reasons; also to make the builds more reproducible - e.g. if you have used a git-checkout but hacked the build-system to make it work on Raspbian, than the users should get those changes too).

The flag could probably renamed to `--no-source-error` though.

**Comment by chr15m** [comment] 2016-02-15 13:26
I think we should tell people about the flag in the warning.

On 15 February 2016 9:22:48 pm AWST, "umläute" <notifications@github.com> wrote:
>it's a feature (see #88).
>
>[i don't see](http://deken.puredata.info/search?name=Gem) that you have
>uploaded any sources for `Gem/0.93.3git54b4b7c`, so `deken` is correct
>in complaining that the sources are missing.
>(deken is dumb; it won't read your version string, see that it contains
>`git`, google for the upstream repository and check whether the
>commit-id has been pushed; it also won't read your notes, mind or
>file-descriptions and parse it for terms like *here are the source:*)
>
>In any case, you can override the complaint with the
>`--no-source-warning` flag.
>
>I'm reluctant to add this info to the error message itself, as i really
>want people to upload the sources.
>(not only for license reasons; also to make the builds more
>reproducible - e.g. if you have used a git-checkout but hacked the
>build-system to make it work on Raspbian, than the users should get
>those changes too).
>
>The flag could probably renamed to `--no-source-error` though.
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/pure-data/deken/issues/118#issuecomment-184206253

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by avilleret** [comment] 2016-02-15 14:02
I understand the need to upload source, but when I tried, it fail : 

~~~~
$ deken upload "Gem-v0.93.3git54b4b7c-(Source)-externals.tar.gz"
Deken 0.1
Environment variable DEKEN_USERNAME is not set and the config file /home/pi/.deken/config does not contain a 'username = ...' entry.
To avoid this prompt in future please add a setting to the config or environment.
Please enter username for http://puredata.info/: avilleret
Please enter password for uploading as 'avilleret': 
Checking puredata.info for Source package for 'Gem/0.93.3git54b4b7c'
Missing sources for 'Gem/0.93.3git54b4b7c'!
~~~~

deken refuses to upload a source package because it's sources are missing
which is annoying...
and that sounds like a bug to my eyes

**Comment by umlaeute** [comment] 2016-02-15 14:29
ah @avilleret, that explains a bit (i was actually missing the 2nd (source) package in your original post).

i guess that's because it's called `(Sources)` in the code and `(Source)` in the documentation.

so the docs should be fixed.
and the flag should be mentioned in the warning...

**Comment by avilleret** [comment] 2016-02-15 14:35
that works, thanks
so it was a just a missing "s" ...

**Closed** 2016-02-15 14:40 UTC
