### ISSUE TITLE
list of externals

### ISSUE THREAD

**Issue by jmmmp** [pure-data/deken#52] opened 2015-06-23 22:50 UTC
is it possible to get a list of externals in the main server?

**Comment by umlaeute** [comment] 2015-06-24 07:54
dupe of #45.

the solution is to commit an *empty* search.
this should be documented.

**Comment by chr15m** [comment] 2015-06-24 11:08
Or we could put a "show all" button. Or perform an empty search when the plugin is first loaded by default, though maybe it's not good to launch an HTTP request without user interaction first.

**Comment by umlaeute** [comment] 2015-06-24 11:18
yep, i strongly oppose to automatic HTTP-requests without user interaction.

how about that:
- as long as the search-box is empty, the button shows "show all", and once the user entered some text, the button label changes to "search" (and back to "show all" if the entry is cleared)?

**Comment by chr15m** [comment] 2015-06-24 11:26
Great!

**Comment by chr15m** [comment] 2015-06-24 11:26
I wonder if we can have greyed-out placeholder text in the search box before they type anything? Either way is good.

**Comment by umlaeute** [comment] 2015-06-24 11:28
i already had the last suggestion implemented and now have implemented the changing button labels.

soon to request pull

**Comment by chr15m** [comment] 2015-06-24 11:31
Ah, great.

My laptop died so I am on my wife's computer. Installing Pd now for more testing.

**Comment by umlaeute** [comment] 2015-06-24 11:36
on rereading i see that i did something different with the "greyed out" text: i really just put a note in the *results* panel.

**Comment by chr15m** [comment] 2015-06-24 11:39
changing the button is probably good enough for the feature.

**Closed** 2015-06-24 11:48 UTC

**Comment by jmmmp** [comment] 2015-06-24 19:58
it does work. a phrase saying "An empty search will provide a complete  
list of externals." after your "Only install..." should be enough.

Another question: assuming that 100s of externals will be submitted, would  
it be better to implement a tag system?

**Comment by umlaeute** [comment] 2015-06-24 20:02
@jmmmp have you tried the recent commit? is it ok?

**Comment by umlaeute** [comment] 2015-06-24 20:03
as for the 100s of externals: i think we should think about that when we are there...

**Comment by jmmmp** [comment] 2015-06-24 23:43
the search warning works.

not sure about waiting that much for the tags - later on people will be  
lazy to add them in, if they already packed all their code...
