### ISSUE TITLE
debian bullseye deken: Self-installation of Deken failed.

### ISSUE THREAD

**Issue by ritsch** [pure-data/deken#283] opened 2022-12-05 11:01 UTC
When running deken on command line:

```
~$ deken --help
Self-installation of Deken failed.
Please paste any errors in the bug tracker at https://github.com/pure-data/deken/issues
```

so I did.
Using debian bullseye with backports.

mfg winfried

**Comment by umlaeute** [comment] 2022-12-05 21:10
> the package shipped in Debian/bullseye?

i just tried the following:

```sh
docker pull deken:bullseye
docker run --rm -ti debian:bullseye
```

and within the docker container:

```
# apt-get update -y
# apt-get full-upgrade -y
# apt-get install -y --no-install-recommends deken
[...]
# export DEKEN_ROOT=yes
# deken --help
Self-installation of Deken failed.
Please paste any errors in the bug tracker at https://github.com/pure-data/deken/issues
# mkdir ~/.deken
# deken --help
usage: deken [-h] [-v] [-q] [--version] [--platform] {package,upload,find,download,verify,install,uninstall,systeminfo} ...

Deken is a packaging tool for Pure Data externals.

positional arguments:
  {package,upload,find,download,verify,install,uninstall,systeminfo}

optional arguments:
  -h, --help            show this help message and exit
  -v, --verbose         Raise verbosity
  -q, --quiet           Lower verbosity
  --version             Outputs the version number of Deken.
  --platform            Outputs a guess of the current architecture.
# deken find zexy
zexy/2.4.1 uploaded by zmoelnigbot on 2022-02-02 17:14:09 for Darwin-amd64-32/Darwin-arm64-32/Linux-amd64-32/Linux-arm64-32/Linux-armv7-32/Linux-i386-32/Windows-amd64-32/Windows-i386-32
	 URL: http://puredata.info/Members/zmoelnigbot/software/zexy/2.4.1/zexy[v2.4.1](Darwin-amd64-32)(Darwin-arm64-32)(Linux-amd64-32)(Linux-arm64-32)(Linux-armv7-32)(Linux-i386-32)(Windows-amd64-32)(Windows-i386-32).dek
	 -----------------------------------------------------------------
#
```

so the trick is *still* to run `mkdir ~/.deken` before using *deken*.

btw, this is a duplicate of https://github.com/pure-data/deken/issues/254, which is almost exactly one year old. :christmas_tree:

**Closed by umlaeute** 2022-12-05 21:10 UTC

**Comment by ritsch** [comment] 2022-12-06 11:19
It is from the debian package.

I think, deken should make a directory .deken, if it needs it, so how can debian package fix this ?

Since /usr/bin/deken  is a shell script, maybe there should be a test for a ${HOME}/.deken dir, if not it should make some. So it can be fixed within deken repo.

else, Did you do a 'reportbug' since closed this issue ?

**Comment by umlaeute** [comment] 2022-12-06 11:25
no, i did not do a `reportbug`; but the issue is fixed in this repository (so I close it here)
