### ISSUE TITLE
deken from bullseye repo fails to run

### ISSUE THREAD

**Issue by reduzent** [pure-data/deken#262] opened 2022-05-06 11:54 UTC
I installed deken from Debian Bullseye (amd64). When running it, I get:

```
roman@bullseye:~$ deken 
Self-installation of Deken failed.
Please paste any errors in the bug tracker at https://github.com/pure-data/deken/issues
```

Sorry, if this is the wrong place for this report. At least, I hope it reaches the correct person.

**Comment by umlaeute** [comment] 2022-05-06 20:56
`which deken`?

**Comment by reduzent** [comment] 2022-05-06 21:05
This happened on a pristine bullseye installation where I hadn't been manually bootstrapping Deken before. In the meanwhile I manually installed Deken. However, I can reproduce on a different machine:

```
roman@mailagent:~$ which deken
/usr/bin/deken
roman@mailagent:~$ deken
Self-installation of Deken failed.
Please paste any errors in the bug tracker at https://github.com/pure-data/deken/issues
roman@mailagent:~$ sudo deken
WARNING: You're currently running as root; probably by accident.
Press control-C to abort or Enter to continue as root.
Set DEKEN_ROOT to disable this warning.
```

**Comment by umlaeute** [comment] 2022-05-06 21:22
ah yes, this is a duplicate of #247 and #254

**Closed by umlaeute** 2022-05-06 21:22 UTC
