### ISSUE TITLE
sourceful uploads

### ISSUE THREAD

**Issue by umlaeute** [pure-data/deken#88] opened 2015-10-28 10:02 UTC
one the biggest issues i have with deken is, that it encourages the upload of totally unreproducible binaries.

i'm not really talking about trust (which is at least thought of with using SHA256,  gpg, ... though it's not fully implemented yet), but the lack of source code (and build systems).

## case study: `creb`

As an example take [creb](http://deken.puredata.info/search?name=creb) (this is just any example which I happen to have stumbled upon; I think everybody involved has acted with the best intentions, but it shows the underlying problem):

### source code

first of all, there are multiple places to obtain the *source code* for creb:
- Tom Schouten's [darcs repository](http://zwizwa.be/darcs/creb/).
 - the buid-system included here creates a big multi-object library `creb.pd_linux`.
- the [Pd-SVN](https://svn.code.sf.net/p/pure-data/svn/trunk/externals/creb/)
 - the build-system included here is *broken* (it seems that some core source-code components have been omitted/deleted in the sync)
 - there is *another* build-system, namely the large monolithic Pd-extended [Makefile](https://svn.code.sf.net/p/pure-data/svn/trunk/externals/Makefile), which builds a number of single-object externals.

Tom (the upstream author) explicitely states:
>  The authoritative source for CREB is the darcs archive.

afaict, there is no "release tarball" available from any party.

it appears that while the two VCSs have been synched in the past, but currently have diverged (slightly).

to confuse things more, the two sources both claim to contain version `0.9.2`.
i guess this is not entirely true, but instead the two sources contain `0.9.2+x` (resp. `0.9.2+y`) and the code just hasn't been updated that it has included updates since the last release.
both `x` and `y` are unknown.

### uploaded packages

we not only have two different origins for the source code, we by now also have multiple `deken` installable packages:

- one uploaded by @chr15m (though attributed to me by the deken search pugin), with the version `v0.0.extended`
- one uploaded by @electrickery, with the version `0.9.2`.
- there's a third one in the queue, as I have uploaded a Debian package `pd-creb` to Debian last night, which (in time) will show up. it has version `0.9.2+darcs20151027-1`

since i was involved in the `v0.0.extended` upload (and have followed the Pd-extended genesis), I can tell approximately how this packages was obtained:
- Pd-extended has been built (automatically) from the SVN. the source code (including that of creb) is available via an [SVN branch](https://pure-data.svn.sourceforge.net/svnroot/pure-data/branches/pd-extended/0.43) and as a [source tarball](http://sourceforge.net/projects/pure-data/files/pd-extended/0.43.4/Pd-extended_0.43.4-source.tar.bz2/download)
- Pd-extended uses a large monolithic [Makefile](https://svn.code.sf.net/p/pure-data/svn/trunk/externals/Makefile) to build externals (including creb)
- the Pd-extended builds for the various platforms have been manually downloaded and unpacked.
- the `creb` directory of those builds have been re-packaged (e.g. merging the i386 and amd64 binaries for linux) and zipped
- and then uploaded via *deken*

for the `0.9.2` upload i know decidedly less.
what I do know is, that this upload (actually: group of uploads) contains single-object externals.
i also know, that the uploader is involved in the [pdlibbuilder build-system](https://github.com/pure-data/pd-lib-builder), is capable of building single-object externals.
i **guess** that the `0.9.2` builds have been produced using the [SVN trunk](https://svn.code.sf.net/p/pure-data/svn/trunk/externals/creb/) around 2015-06-18, using either the monolithic Makefile or the *pdlibbuilder*, but that's only a wild guess.

for the `0.9.2+darcs20151027-1` i know decidedly more. for one thing, it was me who did it :-) however there is more: Debian requires me to do a *sourceful upload*, therefore binaries are accompanied (in the Debian archive, not necessarily on the end user's machine) by *full sources* including the actually used build-system.

## reproducibility

my main concern here is to be able to re-produce package builds.
if I am in dire need for a binary for the `foo128` architecture and the uploader's harddisk that contained a fixed buildsystems (and some other bugfixes) used for the `i286` builds has been drowned, it is of little help that the library is Open Source (esp. since the service that hosted the original library has gone bankrupt a decade ago).

## so what?
i would like do discuss how we could encourage uploaders to also provide the full source code they used for building a binary.

**Comment by chr15m** [comment] 2015-10-28 10:25
Sounds great. This is quite out of my depth but I agree it is important.

**Comment by chr15m** [comment] 2015-10-28 10:27
I guess the first thing would be to have a protocol / layout for including source code in the zip, and a new section in the file name tags.

**Comment by umlaeute** [comment] 2015-10-28 11:05
right. i guess it might be as simple as providing a new *architecture* `source` and reminding the people to also upload a source-package.

     $ deken upload frozzel-v0.12-(Linux-amd64-64)-externals.tar.gz
     [...]
     WARN: Your package seems to not include source code.
     WARN: Please also upload a source package: 'frozzel-v0.12-(source)-externals.tar.gz'
     $ deken upload frozzel-v0.12-(source)-externals.tar.gz
     [...]
     $

or doing it right from the beginning:

     $ deken upload snarkl-v3.14-(Linux-armv4l-32)(source)-externals.tar.gz
     [...]
     $

the WARNing is probably too easy to overlook though.

and i'm not sure how to properly detect the `source` architecture with`deken package` (look out for `*.c`, `*.cc`, `*.cpp`, `*.cxx`, `*.h`, `*.hpp` files?)

**Comment by chr15m** [comment] 2015-10-28 12:03
That sounds like a good first iteration to me. :+1:

We could be a bit more strict and require `--no-source-warning`. If the flag is not included then the upload will be blocked.

**Comment by electrickery** [comment] 2015-12-26 15:33
Currently trying to get a new cyclone release out the door. Most of the platform names are clear, but the MacOSX 64-bit is still a bit ambiguous. 

Is it (Darwin-X86_64-32) or (Darwin-X86_64-64)? The github developer/README.md mentions "Darwin-x86_64-32", but the Wikipedia pages for MacOSX and XCode do not mention such a hybrid binary version.

Deken packaging doesn't work for my old MacOSX 10.5, so I create a simple packaging script for this. Sources will be included: 
tar cvzf ${PACKAGE}-${VERSION}(Darwin-ppc-32)(Darwin-i386-32)(Darwin-X86_64-64)(source)-externals.tgz ${PACKAGE}

**Comment by umlaeute** [comment] 2015-12-26 21:17
@electrickery i have a draft implementation (PR #102) ready, which uses `(Sources)` as the pseudo-architecture for source-uploads, so your tar-command should look more like

    tar cvzf ${PACKAGE}-${VERSION}(Darwin-ppc-32)(Darwin-i386-32)(Darwin-X86_64-32)(Sources)-externals.tgz ${PACKAGE}

**Comment by umlaeute** [comment] 2015-12-26 21:21
as for the bit-field, i think this has been dicussed in #83 (with no proper outcome, though for whatever reasons it seems that deken uses `32` on OSX/amd64, so the architecture string is `(Darwin-x86_64-32)`.

also could you please be more verbose on "Deken packaging doesn't work for my old MacOSX 10.5" (though in the appropriate issue (may be a new one))

**Comment by electrickery** [comment] 2015-12-27 09:28
@umlaeute: MacOSX 10.5 is not supported by modern browsers, and the CA certificate store cannot be updated. So any HTTPS connection will fail. The problem is with the obsolete system, not deken.

**Closed** 2016-02-05 03:40 UTC
Labels: deken (cmdline), high priority
