### ISSUE TITLE
developer command line tool dependency

### ISSUE THREAD

**Issue by avilleret** [pure-data/deken#123] opened 2016-03-14 19:45 UTC
on an almost new Ubuntu installation, I would like to use the developer command line tool, but I have to install some few extra dependencies :

```
python-dev libffi-dev libssl-dev
```

this might be added to the developer readme

**Comment by umlaeute** [comment] 2016-06-08 12:17
hmm, are you saying that on a fresh installation, you cannot use the `deken` [Debian](https://packages.debian.org/search?keywords=deken) or [Ubuntu](http://packages.ubuntu.com/search?keywords=deken) package?
because both lack the dependencies on any `-dev` package

**Comment by avilleret** [comment] 2016-06-08 12:54
sorry, I didn't know that there is a pd-deken package.
I was referring to https://github.com/pure-data/deken/tree/master/developer#get-started
And to get started, I had to install some extra packages, maybe the developer Readme could be updated ?

**Comment by umlaeute** [comment] 2016-06-08 14:02
ah yes, because doing it *that* way will `pip install` a couple of packages, which might require compiling stuff.
thanks for pointing me to the relevant documentation that needs to be fixed...

**Comment by umlaeute** [comment] 2017-10-23 19:02
i think this is a dupe of #108, which has been fixed: the cmdline tool will spit out a list of suggested packages if things go bonkers.

**Closed by umlaeute** 2017-10-23 19:02 UTC
Labels: deken (cmdline)
